#!/bin/bash
docker run -d -p 8080:80 --name nodejs -v ${HOME}/docker/data/nodejs:/data dellarte/rpi-nodejs /bin/bash -c "nodemon -e js,html,ejs --ignore logs/ --ignore static/js/ app.js 2>logs/app.error"
